#!/bin/bash
intltool-extract --type=gettext/glade usr/share/htv/hypnotix.ui
intltool-extract --type=gettext/glade usr/share/htv/shortcuts.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=hypnotix.pot usr/lib/htv/*.py generate_desktop_files usr/share/htv/hypnotix.ui.h usr/share/htv/shortcuts.ui.h
rm -f usr/share/htv/*.ui.h
